### ISSUE TITLE
Fit in window

### ISSUE THREAD

**Issue by everyonesdesign** [component/tip#54]
Now component/tip positions itself in [such way](https://github.com/component/tip/blob/master/index.js#L355) (e.g. top position is chosen):
the dropdown should be centered relative to target horizontally and should be over target by its height.
But this algorithm don't correct cases when the dropdown sticks out of window (horizontally of vertically).
May be we should implement viewport-bound behavior as an option?

**Comment by everyonesdesign** [comment]
https://github.com/component/tip/pull/53 - there's a pull request on it. Is it appropriate for the component or we should change it somehow?

**Comment by jmagnusson** [comment]
Would be super nice to have this.
